backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'slideimages'
    label: 'SlideImages'
    format: 'json'
    folder: 'assets/content/SlideImages'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'スライド画像', name: 'image', widget: 'image' }
  - name: 'about'
    label: 'About'
    format: 'json'
    folder: 'assets/content/About'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: '更新日',
          name: 'update-date',
          widget: 'datetime',
          format: 'YYYY/MM/DD-HH:mm:ss',
        }
      - { label: 'メイン画像', name: 'image', widget: 'image' }
      - { label: 'コンテンツ', name: 'content', widget: 'markdown' }
      - { label: 'サムネイル画像', name: 'thumbnail', widget: 'image' }
      - { label: 'プロフィール', name: 'profile', widget: 'markdown' }
  - name: 'news'
    label: 'News'
    format: 'json'
    folder: 'assets/content/News'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: '作成日',
          name: 'created-date',
          widget: 'datetime',
          format: 'YYYY/MM/DD-HH:mm:ss',
        }
      - {
          label: '更新日',
          name: 'update-date',
          widget: 'datetime',
          format: 'YYYY/MM/DD-HH:mm:ss',
        }
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: 'メッセージ', name: 'message', widget: 'markdown' }
  - name: 'item'
    label: 'Item'
    format: 'json'
    folder: 'assets/content/Item'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: '作成日',
          name: 'created-date',
          widget: 'datetime',
          format: 'YYYY/MM/DD-HH:mm:ss',
        }
      - {
          label: '更新日',
          name: 'update-date',
          widget: 'datetime',
          format: 'YYYY/MM/DD-HH:mm:ss',
        }
      - { label: 'URL', name: 'pagepath', widget: 'string' }
      - { label: '名前', name: 'name', widget: 'string' }
      - { label: '価格', name: 'price', widget: 'string' }
      - { label: 'BoothURL', name: 'shopaddress', widget: 'string' }
      - {
          label: 'カテゴリー',
          name: 'category',
          widget: 'select',
          options: ['アクセサリー', '日用品', '事務用品', 'その他'],
          default: ['アクセサリー'],
        }
      - label: 'タグ'
        name: 'tags'
        widget: 'list'
        fields:
          - { label: 'タグ名', name: 'tagname', widget: 'text' }
      - { label: 'アイテムの説明', name: 'info', widget: 'markdown' }
      - { label: '補足情報', name: 'specification', widget: 'markdown' }
      - {
          label: 'Image1',
          name: 'image1',
          widget: 'image',
          default: '/images/kontikushow-dummy-big.jpg',
        }
      - {
          label: 'Image2',
          name: 'image2',
          widget: 'image',
          default: '/images/kontikushow-dummy-big.jpg',
        }
      - {
          label: 'Image3',
          name: 'image3',
          widget: 'image',
          default: '/images/kontikushow-dummy-big.jpg',
        }
