backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'latestnews'
    label: 'LatestNews'
    format: 'json'
    folder: 'assets/content/LatestNews'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Thumbnail', name: 'image', widget: 'image' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY/MM/DD',
        }
      - { label: 'Content', name: 'content', widget: 'markdown' }
