backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: 'slideimages'
    label: 'SlideImages'
    format: 'json'
    folder: 'assets/content/SlideImages'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'SlideImage', name: 'image', widget: 'image' }
  - name: 'latestnews'
    label: 'LatestNews'
    format: 'json'
    folder: 'assets/content/LatestNews'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Thumbnail', name: 'image', widget: 'image' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY/MM/DD',
        }
      - { label: 'Content', name: 'content', widget: 'markdown' }
  - name: 'about'
    label: 'About'
    format: 'json'
    folder: 'assets/content/About'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'MainImage', name: 'image', widget: 'image' }
      - { label: 'Content', name: 'content', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Profile', name: 'profile', widget: 'markdown' }
  - name: 'item'
    label: 'Item'
    format: 'json'
    folder: 'assets/content/Item'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'ItemName', name: 'name', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'ShopURL', name: 'shopaddress', widget: 'string' }
      - { label: 'ItemInfo', name: 'info', widget: 'markdown' }
      - {
          label: 'ItemSpecification',
          name: 'specification',
          widget: 'markdown',
        }
      - {
          label: 'Image1',
          name: 'image1',
          widget: 'image',
          default: '/images/kontikushow-dummy.jpg',
        }
      - {
          label: 'Image2',
          name: 'image2',
          widget: 'image',
          default: '/images/kontikushow-dummy.jpg',
        }
      - {
          label: 'Image3',
          name: 'image3',
          widget: 'image',
          default: '/images/kontikushow-dummy.jpg',
        }
